### ISSUE TITLE
Change colors for work or break time

### ISSUE THREAD

**Issue by pprw** [TatriX/pomidor#12]
With my emacs theme (tango-dark), the work time and break time are both green (the break is in a lighter green).

Here is a screenshot:

![capture d ecran_2018-01-29_12-09-37](https://user-images.githubusercontent.com/5262986/35507515-4df599c4-04ed-11e8-9f67-43233bbfb3e3.png)

I would like to change either the color for the work time or the break time. I am thinking of replacing the green for work time by red or keep it and replace the break color with blue. These color properties are inherited from "success" and "font-lock-keyword-face". How can I change these without changing other things in my configuration?

**Comment by TatriX** [comment]
You may use `M-x customize-group pomidor` or edit your theme by looking into `defface` in the source code.

**Comment by pprw** [comment]
Thanks for the answer, I used commands such as  `((t (:foreground "#00ff00")))` to personnalize the colors for me. 

I post here the color config if it could save some time to someone:
```

   pomidor face for break
Lisp expression: ((t (:foreground "#00ff00")))

   pomidor face for overwork
Lisp expression: (( t (:foreground "#00abff")))

   pomidor face for skip
Lisp expression: (( t (:foreground "#abbac3")))

   pomidor face for work
Lisp expression: ((t (:foreground "#ff0000")))

```
Result:
![capture d ecran_2018-01-29_14-09-26](https://user-images.githubusercontent.com/5262986/35511971-561b5ace-04fe-11e8-9200-eab7f74a5a3b.png)

**Comment by TatriX** [comment]
I've added your color theme to the readme as an example of customization. Thanks!
