### ISSUE TITLE
Crashes emacs

### ISSUE THREAD

**Issue by ayrat555** [TatriX/pomidor#13]
Crashes emacs on break end

emacs 25.3

P.S. I just wanted to take a little rest 😢

**Comment by TatriX** [comment]
Could you please try with `emacs -Q`?

**Comment by ayrat555** [comment]
@TatriX but all my emacs packages (including pomidor) are defined in ```init.el``` file. ```-Q ``` option stops emacs from loading it

**Comment by TatriX** [comment]
Sure, but this way we can find if the `pomidor.el` causes the crash or not.

**Comment by ayrat555** [comment]
so I started with emacs with ```-Q``` and manually loaded pomidor.el. And yes, it crashed

**Comment by TatriX** [comment]
Ok, could you please do several things:
1) get a [stackstrace](https://www.gnu.org/software/emacs/manual/html_node/emacs/Crashing.html)
2) try disable sounds

**Comment by ayrat555** [comment]
@TatriX Disabling sounds solved the crashing problem. Thank you

**Comment by TatriX** [comment]
Could you please run something like this (adjust path to `wav` file):
```sh
/usr/bin/emacs -Q --batch --eval '(play-sound-file "~/.emacs.d/pomidor/tack.wav")'
```
and see if it's crashes.

**Comment by ayrat555** [comment]
```❯ emacs -Q --batch --eval '(play-sound-file "/Users/ayrat/.emacs.d/elpa/pomidor-20171214.727/tack.wav")'```

Output:
```This Emacs binary lacks sound support```

**Comment by TatriX** [comment]
Could you please check `sound` branch. I did a fix to prevent crashing and also added an option to use external program to play the sounds:
```lisp
(setq pomidor-play-sound-file
      (lambda (file)
        (start-process "my-pomidor-play-sound"
                       nil
                       "mplayer"
                       file)))
```

**Comment by ayrat555** [comment]
@TatriX It's awesome but MacOs does not have any installed terminal players by default. Maybe you can do something like [Alarm Bell](https://www.emacswiki.org/emacs/AlarmBell)?

**Comment by TatriX** [comment]
You can run any code in that function, just change `(start-proces ...` with whatever you wish.

**Comment by ayrat555** [comment]
I moved to Ubuntu-based distro, now everything's fine. Thank you for your
help.

On 23 Feb 2018 17:53, "TatriX" <notifications@github.com> wrote:

You can run any code in that function, just change (start-proces ... with
whatever you wish.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TatriX/pomidor/issues/13#issuecomment-368030990>, or mute
the thread
