### ISSUE TITLE
Please provide API for querying if pomidor is running

### ISSUE THREAD

**Issue by Fuco1** [TatriX/pomidor#21]
I would like to capture tasks during a running pomodoro with org mode and have some tags attached automatically so that I can later go back and review how many interuptions there were.

I could use some predicate such as `pomidor-running-p` or `pomidor-active-p` for that.  I could use the timer or some internals but I'm sure that's not a great idea as you might change that any time.

Thanks for the awesome package!

**Comment by TatriX** [comment]
Hi, thanks!
 I'll try to to that.
PR is welcome if you want it faster ;)

**Comment by TatriX** [comment]
I finally added it ;)

**Comment by Fuco1** [comment]
Time to remove my timer hacks :D Thanks!
