### ISSUE TITLE
Add some way to disable the tick-tack sound playing.

### ISSUE THREAD

**Issue by Fuco1** [TatriX/pomidor#22]
I can't find an option to turn this on.  I find it quite annoying when I want to listen to music :o: 

For now I've commented out the body of `pomidor--tick-tack`

**Comment by TatriX** [comment]
Check [README](https://github.com/TatriX/pomidor#customization):
```elisp
(setq pomidor-sound-tick nil
      pomidor-sound-tack nil)
```

**Comment by Fuco1** [comment]
Hey, thanks for the quick answer!

I think it would still be worth it to have a customize option for toggling sound.  The reason is that customize makes things discoverable.  I usually browse the package's configuration through that interface and I know many other people do also.  So a global toggle there would be useful.

Probably these other sound variables should also be converted to `defcustom`s.

**Comment by TatriX** [comment]
Oh, I was sure it's in customization interface.

**Comment by TatriX** [comment]
Closed by #25
