### ISSUE TITLE
Endless loop of warning "This Emacs binary lacks sound support"

### ISSUE THREAD

**Issue by rnkn** [TatriX/pomidor#24]
The function `pomidor-play-sound-file-emacs`, which appears to be called once per second, will raise a warning upon each call if `play-sound-internal` is unbound, which it is for GUI and console Emacs 26.1 on macOS.

https://github.com/TatriX/pomidor/blob/30004b21714b53d22041514d905e1876c5cedd4b/pomidor.el#L115

Deleting this line resolves the problem.

**Comment by rnkn** [comment]
Excellent package btw.

**Comment by TatriX** [comment]
Thank you. You can [override](https://github.com/TatriX/pomidor/tree/30004b21714b53d22041514d905e1876c5cedd4b#sound) that. If you think it should be handled differently, please feel free to reopen the issue.

**Comment by rnkn** [comment]
Ah I see, thanks. I'd only suggest this might be better as a `defcustom`.

(I think GitHub change a while back and only you can reopen issues these days.)

**Comment by TatriX** [comment]
Yes, sounds like a good idea. PR is welcome ;)

**Comment by TatriX** [comment]
Closed by #25
