### ISSUE TITLE
[Request] Long Break

### ISSUE THREAD

**Issue by mrbig033** [TatriX/pomidor#32]
Many Pomodoros have a longer break after 4 intervals. I believe that would be a nice addition to this mode.

Thanks!

**Comment by TatriX** [comment]
This sounds lively!
Do you have ideas on how this should be explained to the user and configured?

**Comment by mrbig033** [comment]
Sure, glad to help!

Just add this to the `Customization` section on README (the values are [the default ones](https://en.wikipedia.org/wiki/Pomodoro_Technique)):

Long breaks:
```elisp
(setq pomidor-breaks-before-long (4)) ; after 4 short breaks, run a long break
(setq pomidor-long-break-seconds (* 20 60)) ; 20 minutes long break time
```
I still don't know how to make a pull request, but I can learn and make further additions to the README (maybe a brief explanation of the Pomodoro technique itself) if you think it would be helpful.

**Comment by TatriX** [comment]
Shall I help you with the PR? I guess to do so I should improve docs and maybe even refactor the code. Do you have any questions up front?

**Comment by mrbig033** [comment]
Yes, I would love some help. 

But I suppose I should wait for you to implement the new feature, then test it and add some friendly instructions to the README.

I can also add more extensive instructions that are more suitable to beginners. I'm not much  of a programmer, but I'm good with words and stuff.

**Comment by TatriX** [comment]
Sorry for the delay, too much stuff happening right now..
Ok, so let's do it this way: I'll add the feature and you'll do a code review and write some docs :) Sounds good?

**Comment by mrbig033** [comment]
Yes, sounds great!

**Comment by wandersoncferreira** [comment]
Hi guys, I can provide some help in this issue as well. This is a very useful feature to be more compliant with the pomodoro technique. Do you guys mind if I join you here?

**Comment by TatriX** [comment]
Please do!

**Comment by mrbig033** [comment]
@wandersoncferreira absolutely not. I´m not really a programmer, but I´d be glad to help with testing and documentation. This is a cool package.

**Comment by mrbig033** [comment]
> ry useful feature to be more compliant with the pomodoro technique.
