### ISSUE TITLE
Pomidor not working after update

### ISSUE THREAD

**Issue by Aodhagan** [TatriX/pomidor#38]
I've been using your package every day now for about a year (thank you btw!) and has worked perfectly. I updated the package for the first time yesterday and now it's not working. 

More specifically, the pomidor function activates correctly when `f12` is pressed but there is no overwork sound when the pomidor timer is completed. Then I can press `space` to switch to break successfully but when `enter` is pressed to activate another pomidoro timer the timer on the UI freezes and the following error is returned in the messages buffer 

`pomidor-should-long-break-p: Symbol’s function definition is void: equalp`

I then need to kill the buffer and start again. 

As for setup Im using emacs 26.1 on Windows 10 and Pomidor is installed using use-package with the elisp code you specify on your readme on pomidor github page. Any ideas what might be gone wrong?

**Comment by wandersoncferreira** [comment]
Hello @Aodhagan seems like a problem of not recognizing the `cl-lib`. 

Could you verify if `(require 'cl-lib)` works in your open session?
If so, can you change `equalp` in the `pomidor.el` by `cl-equalp` and try to reproduce the error?

Unfortunately, I cannot reproduce this error here, so I need your help on that.

**Comment by Aodhagan** [comment]
Thanks for the reply. `(require 'cl-lib)` does indeed work in my open session. No errors returned. I changed two instances `equalp` to `cl-equalp` in the `pomidor.el` file under `pomidor-should-long-break-p` and `pomidor--valid-session-dates`.

Unfortunately after saving and restarting the session the same behaviour still occurs as described above. Would updating my emacs version potentially help in anyway?

**Comment by wandersoncferreira** [comment]
I am using Emacs 26.3, so yours should be fine bc `cl-lib` was introduced in Emacs 24.3. Can you check if there is no `.elc` file from a old instance laying around? I am getting out of ideas, but as usual, the last resource is a clean install. Have you tried?

**Comment by Aodhagan** [comment]
Hmm deleted the pomodor.elc file in the promodor directory in elpa dir and now it's working. It's getting late so will test more thoroughly in the morning and confirm. Thanks for the help!

**Comment by Aodhagan** [comment]
Tested again today. It froze again on the commencement of my first break today. So I undone the changes you suggested initially and replaced `cl-equalp` with `equalp` and restarted. There hasn't been a problem since. So the problem was with the .elc it seems. Thanks very much for your time and for your work with Pomodor. It's really helping with getting my work done.
