### ISSUE TITLE
Issue with elisp and "equalp"

### ISSUE THREAD

**Issue by Fedge1** [TatriX/pomidor#39]
Hello,
First I love your implementation of the Pomodoro technique.

But recently it stopped working on my emacs (26.3), running on Solus Linux (4.1), oh, and emacs as EXWM.  Anyways, it was throwing an error with "equalp".  I did some searching, and found that "equalp" is short for "cl-equalp", so I changed the two instances of "equalp" to "cl-equalp" in your "pomidor.el" file, and it works again.

I'm not sure why it broke?  Well I'm sure it's because I did do some updates.  Anyways, just wanted to note this issue, as I assume "equalp" not being recognized is because of an update to emacs?  But maybe it just some weird issue with my system?

**Comment by wandersoncferreira** [comment]
Hello @Fedge1 , thanks for open the issue. We had other similar report recently about this, however in that case the OP had an old pomidor.elc file that was preventing the updated version to take effect properly.

But prior to the new implementations of pomidor-history this package was not using 'equalp'. When you updated you got this new features.

I am wandering if there is something we can do to improve users access to how solve this problem if it appears. For example, i) FAQ section in the readme, ii) rename the variables to cl-equalp as you did or even try to remove this two equalities and use something not from cl-lib.

What you guys think?

**Comment by TatriX** [comment]
So, `equalp` is an alias to `cl-equalp`. So I guess we can rename all occurrences of it to `cl-` version.

**Comment by wandersoncferreira** [comment]
Can you submit a PR with this change @Fedge1 ?

**Comment by Fedge1** [comment]
Sorry, I'm new to all this.  This was my first post to github.  I try a 'pull request'....

**Comment by wandersoncferreira** [comment]
No pressure, I found this link with a good step-by-step about how to submit a PR: https://opensource.com/article/19/7/create-pull-request-github

Thanks for helping!

**Comment by Fedge1** [comment]
I know very little about programming.  My 'fix' was really a hack that worked.  I understand the whole idea of github, and the theory on how I would do a pull request, but it'll take me while to figure out in practice, and I'm quite busy with work at the moment...

**Comment by wandersoncferreira** [comment]
Oh, ok no problem. I can make the change in a few moments. o/

**Comment by TatriX** [comment]
Please reopen if any. Thanks!
