### ISSUE TITLE
Not work in Emacs 27.1

### ISSUE THREAD

**Issue by ChaoticEvil** [TatriX/pomidor#46]
The latest stable Emacs release for Mac OS is 27.1 When I try to install a package, I get an error:

```
In toplevel form:
pomidor.el: 30: 1: Error: Cannot open load file: No such file or directory, alert
```

**Comment by wandersoncferreira** [comment]
Hello @ChaoticEvil , how are you installing `pomidor`? The `alert` package is an external dependency to the project, but it will get downloaded if you use `package.el` or `use-package` to install it.

If you are cloning this repository and adding it to your `load-path` then you will need to download the dependencies manually too.

**Comment by ChaoticEvil** [comment]
Hi. I using `use-package`:

```
(use-package pomidor
    :ensure t)
```

But, after install alert manually (over package-intall) - pomidor installed and worked ok.

**Comment by TatriX** [comment]
I'm going to close this on an assumption that it was a strange coincidence and others are not affected by this, because I can't see how we can move forward here. Feel free to reopen if _you_ are affected as well.
