### ISSUE TITLE
Journal entry

### ISSUE THREAD

**Issue by dagomar** [TatriX/pomidor#47]
Hi,

disclaimer: super new to emacs.

I was wondering if it's possible to have an automated journal entry after a timer has finished? What I'd like to achieve is that after a pomodoro has finished I jot down what I have done during the pomodoro. Now I can manually do this, but what I'd like is that a window automatically opens with a log entry ready to type when the pomodoro has finished. 

Is this something that can be achieved? Anyone has a pointer? Thanks!

**Comment by TatriX** [comment]
Hi!
I'm not entirely sure what specifically you want your workflow to be, but let's say you want to run some action when you press `SPC` to start "break" period.
```lisp
(defun my-pomidor-log ()
    ;; Check that there is actually a break, rather then break new timer start
    (when (pomidor-break-duration)
      ;; Here you want to run some code to actually open journal window
      (message "Open journal here")))
;; Run `my-pomidor-log` after one presses `SPC`
(advice-add #'pomidor-break :after #'my-pomidor-log)
```
