### ISSUE TITLE
Can't see history of sessions: Symbol’s function definition is void: parse-iso8601-time-string

### ISSUE THREAD

**Issue by niyumard** [TatriX/pomidor#48]
Hi,
I'm new to Emacs and I love pomidor, however I get this error each time I run pomidor-history:
`Symbol’s function definition is void: parse-iso8601-time-string`
I'm using Doom Emacs and here's an example of the json file that is saved:
`[{"started":"2020-11-21T18:18:07","break":"2020-11-21T18:43:16","stopped":"2020-11-21T18:49:10","snooze":true,"session-ended":"2020-11-21T20:43:38"},{"started":"2020-11-21T18:49:10","break":"2020-11-21T19:17:38","stopped":"2020-11-21T19:23:44","snooze":true,"session-ended":"2020-11-21T20:43:38"},{"started":"2020-11-21T19:23:44","break":null,"stopped":"2020-11-21T19:26:37","snooze":null,"session-ended":"2020-11-21T20:43:38"},{"started":"2020-11-21T20:16:38","break":"2020-11-21T20:41:50","stopped":"2020-11-21T20:43:38","snooze":null,"session-ended":"2020-11-21T20:43:38"}]`

**Comment by wandersoncferreira** [comment]
Probably related to your Emacs version. This function exists inside the `parse-time.el` module and looking at the history of the package here (https://github.com/emacs-mirror/emacs/blame/master/lisp/calendar/parse-time.el) it seems the function has been around for a while.

What is your Emacs version? Thanks for reporting.

**Comment by niyumard** [comment]
Apparently I needed to uncomment `calendar` in `.doom.d/init.el`, with that package installed I can see history very easily. Thank you!

**Comment by TatriX** [comment]
`calendar` is a builtin package. I'm not sure if we need to require it or `parse-time` explicitly. I'm going to close the issue, unless someone has an idea on how to move this forward. Please feel free to reopen.
