### ISSUE TITLE
Clean install fail

### ISSUE THREAD

**Issue by wandersoncferreira** [TatriX/pomidor#49]
Hello @TatriX how are you? Hope everything is fine over there.

I just wanted to open this issue to keep track of one issue, I installed the pomidor package on a clean Emacs inside Windows WSL2 (Emacs 27) and it failed using `use-package`:

```elisp
(use-package pomidor
  :ensure t)

;; In toplevel form:
;; pomidor.el:30:1:Error: Cannot open load file: No such file or directory, alert
```

I had to install `alert` before it. I was certain that use-package should figure this dependency by itself and install for me. Idk where the problem is right now, but got me intrigued. If I have some time I can dig into this.

Thanks

**Comment by TatriX** [comment]
Hi! I'm good thank you! Hope you are well too!

Can you reproduce the problem easily?

**Comment by YorozuyaDev** [comment]
I have the same bug, I installed your mode yesterday in my laptop and works great, but in my desktop computer after install give me the same error.  I tried to install cloning the repo but it didn't help. Thanks ^^

**Comment by ayrat555** [comment]
I'm experiencing the same issue

**Comment by TatriX** [comment]
I noticed there was a `.` in the `Package-Requires:` header. Perhaps that was a problem.
