### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by AdelleBernal** [TatriX/pomidor#54]
No probs, just when installing from Melpa:

```emacs-lisp
In toplevel form:
pomidor.el:30:1: Warning: Package cl is deprecated
pomidor.el:217:1: Warning: defvar `pomidor-header-session-name-separator'
    docstring wider than 80 characters
```

**Comment by TatriX** [comment]
Oh, sorry, this totally got lost in my inbox.
Looks like these warnings are no longer relevant. At least I've got no warnings when installing with `(package-install)`
