### ISSUE TITLE
Interruption during pomodoro

### ISSUE THREAD

**Issue by dkrmr** [TatriX/pomidor#8]
It'll be nice to record interruptions during a pomodoro, with a message indicating the nature of the interruption, to use later for the review phase.

Is there any plan to add this feature ?

Thx for your work :)

**Comment by TatriX** [comment]
Basically you want to add a message when you stop your timer?

**Comment by dkrmr** [comment]
No, the timer is still running.
In a pomodoro you can have internal or external interruptions. Recording them are useful for the review phase. See: https://facilethings.com/blog/en/interruptions-on-pomodoro

**Comment by TatriX** [comment]
Oh, ok.

**Comment by TatriX** [comment]
I think this feature doesn't fit very well. Probably you want a more sophisticated tool like https://github.com/lolownia/org-pomodoro or maybe just use a separate `org` file.
